# Generated by Django 5.0.3 on 2024-04-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0005_alter_book_author_alter_book_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=40),
        ),
    ]
